import { Navbar } from "@/components/navbar/navbar";
import { QueryProvider } from "@/components/query-client-provider";
import { ThemeProvider } from "@/components/theme-provider";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["900", "800", "700", "600", "500", "400", "300"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryProvider>
      <html lang="en">
        <body className={poppins.className}>
          <ThemeProvider attribute="class" forcedTheme="dark">
            <Navbar />
            {children}
          </ThemeProvider>
        </body>
      </html>
    </QueryProvider>
  );
}
